//! The DRBD resource file, rendered whole.
//!
//! Like corosync.conf, a resource file is generated state: the record in the
//! console is the source of truth, and `/etc/drbd.d/<resource>.res` is
//! overwritten, never merged. Everything that differs between the two
//! topology regimes arrives here as a [`ReplicationPolicy`] — this module
//! never asks how many nodes the cluster has, because that decision belongs
//! to the topology engine and nowhere else.

use std::net::Ipv4Addr;

use lumen_cluster::topology::ReplicationPolicy;
use lumen_cluster::VolumeRecord;

use crate::model::zvol_path;

/// One member's seat as the renderer needs it: the record's seat joined with
/// the Core address the cluster's network definition gives that node.
#[derive(Debug, Clone)]
pub struct RenderSeat {
    pub node: String,
    pub pool: String,
    pub core_address: Ipv4Addr,
}

/// A fresh replication shared-secret: 32 alphanumeric characters, embedded
/// in the rendered file and pushed to each member over the peer channel —
/// exactly the corosync authkey's path, and like the authkey it is never
/// part of the membership record, because a gossiped secret is a distributed
/// one.
pub fn generate_secret() -> String {
    use rand::distributions::Alphanumeric;
    use rand::Rng;
    rand::thread_rng()
        .sample_iter(&Alphanumeric)
        .take(32)
        .map(char::from)
        .collect()
}

/// Render one volume's resource file. `seats` must be the volume's replicas
/// in record order — the index is the DRBD node-id, and node-ids must never
/// change for the life of the resource.
pub fn resource_file(
    resource: &str,
    cluster: &str,
    volume: &VolumeRecord,
    seats: &[RenderSeat],
    policy: &ReplicationPolicy,
    secret: &str,
) -> String {
    let mut out = String::new();
    out.push_str("# Generated by Lumen. Changes here are overwritten; the volume\n");
    out.push_str("# record in the console is the source of truth.\n");
    out.push_str(&format!("resource \"{resource}\" {{\n"));

    // auto-promote is the design: the device promotes when libvirt opens it
    // on the node starting the machine, DRBD itself refuses a second writer,
    // and Pacemaker manages no promotion at all. The regime's quorum or
    // fencing options below are what make that safe.
    out.push_str("    options {\n");
    out.push_str("        auto-promote yes;\n");
    if policy.volume_quorum {
        // Three replicas in the quorum regime: the volume carries its own
        // majority, and losing it suspends I/O rather than serving stale
        // writes — integrity over availability, always.
        out.push_str("        quorum majority;\n");
        out.push_str("        on-no-quorum suspend-io;\n");
    }
    out.push_str("    }\n");

    out.push_str("    net {\n");
    out.push_str("        protocol C;\n");
    out.push_str("        cram-hmac-alg sha256;\n");
    out.push_str(&format!("        shared-secret \"{secret}\";\n"));
    out.push_str("    }\n");

    if policy.fence_peer_through_pacemaker {
        // The two-node regime: on a lost peer, suspend I/O and outdate the
        // peer through Pacemaker before resuming. This is what stands in
        // for quorum where there is no majority to have.
        out.push_str("    disk {\n");
        out.push_str("        fencing resource-and-stonith;\n");
        out.push_str("    }\n");
        out.push_str("    handlers {\n");
        out.push_str("        fence-peer \"/usr/lib/drbd/crm-fence-peer.9.sh\";\n");
        out.push_str("        after-resync-target \"/usr/lib/drbd/crm-unfence-peer.9.sh\";\n");
        out.push_str("    }\n");
    }

    for (index, seat) in seats.iter().enumerate() {
        out.push_str(&format!("    on \"{}\" {{\n", seat.node));
        out.push_str(&format!("        node-id {index};\n"));
        out.push_str(&format!(
            "        address {}:{};\n",
            seat.core_address, volume.port
        ));
        out.push_str("        volume 0 {\n");
        out.push_str(&format!("            device minor {};\n", volume.minor));
        out.push_str(&format!(
            "            disk /dev/zvol/{};\n",
            zvol_path(&seat.pool, cluster, &volume.name)
        ));
        out.push_str("            meta-disk internal;\n");
        out.push_str("        }\n");
        out.push_str("    }\n");
    }

    out.push_str("    connection-mesh {\n");
    let hosts: Vec<String> = seats.iter().map(|s| format!("\"{}\"", s.node)).collect();
    out.push_str(&format!("        hosts {};\n", hosts.join(" ")));
    out.push_str("    }\n");

    out.push_str("}\n");
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use lumen_cluster::VolumeSeat;

    fn volume() -> VolumeRecord {
        VolumeRecord {
            name: "vm-101-disk-0".into(),
            size_bytes: 10 << 30,
            zvol_bytes: (10 << 30) + (1 << 20),
            port: 7788,
            minor: 3,
            replicas: vec![
                VolumeSeat {
                    node: "alpha-1".into(),
                    pool: "tank".into(),
                },
                VolumeSeat {
                    node: "alpha-2".into(),
                    pool: "vault".into(),
                },
            ],
        }
    }

    fn seats() -> Vec<RenderSeat> {
        vec![
            RenderSeat {
                node: "alpha-1".into(),
                pool: "tank".into(),
                core_address: "10.10.0.1".parse().unwrap(),
            },
            RenderSeat {
                node: "alpha-2".into(),
                pool: "vault".into(),
                core_address: "10.10.0.2".parse().unwrap(),
            },
        ]
    }

    #[test]
    fn the_two_node_regime_fences_through_pacemaker_and_carries_no_quorum() {
        let policy = ReplicationPolicy {
            fence_peer_through_pacemaker: true,
            volume_quorum: false,
        };
        let res = resource_file(
            "alpha-vm-101-disk-0",
            "alpha",
            &volume(),
            &seats(),
            &policy,
            "s3cret",
        );
        assert!(res.contains("protocol C;"));
        assert!(res.contains("auto-promote yes;"));
        assert!(res.contains("fencing resource-and-stonith;"));
        assert!(res.contains("crm-fence-peer.9.sh"));
        assert!(res.contains("crm-unfence-peer.9.sh"));
        assert!(!res.contains("quorum majority"), "no majority of two");
        assert!(res.contains("shared-secret \"s3cret\";"));

        // Each seat: its own pool's zvol, its Core address, the shared port,
        // and a node-id fixed by record order.
        assert!(res.contains("node-id 0;"));
        assert!(res.contains("address 10.10.0.1:7788;"));
        assert!(res.contains("disk /dev/zvol/tank/lumen/alpha-vm-101-disk-0;"));
        assert!(res.contains("node-id 1;"));
        assert!(res.contains("address 10.10.0.2:7788;"));
        assert!(res.contains("disk /dev/zvol/vault/lumen/alpha-vm-101-disk-0;"));
        assert!(res.contains("device minor 3;"));
        assert!(res.contains("meta-disk internal;"));
        assert!(res.contains("hosts \"alpha-1\" \"alpha-2\";"));
    }

    #[test]
    fn a_three_replica_quorum_volume_carries_its_own_majority_instead() {
        let policy = ReplicationPolicy {
            fence_peer_through_pacemaker: false,
            volume_quorum: true,
        };
        let res = resource_file(
            "beta-vm-7-disk-0",
            "beta",
            &volume(),
            &seats(),
            &policy,
            "s3cret",
        );
        assert!(res.contains("quorum majority;"));
        assert!(res.contains("on-no-quorum suspend-io;"));
        assert!(!res.contains("fencing resource-and-stonith"));
        assert!(!res.contains("crm-fence-peer"));
    }

    #[test]
    fn a_two_replica_quorum_volume_carries_neither_mechanism() {
        // Two replicas in a three-node cluster: no majority to count, and
        // cluster-level quorum and fencing are what protect it.
        let policy = ReplicationPolicy {
            fence_peer_through_pacemaker: false,
            volume_quorum: false,
        };
        let res = resource_file("beta-v", "beta", &volume(), &seats(), &policy, "s");
        assert!(!res.contains("quorum majority"));
        assert!(!res.contains("fencing resource-and-stonith"));
        assert!(res.contains("auto-promote yes;"));
    }
}
