//! The topology engine: one renderer, two regimes.
//!
//! Everything that differs between a two-node cluster and a three-to-five
//! node cluster is decided here and nowhere else. The rest of the crate — and
//! `lumen-drbd` after it — asks this module what to write rather than
//! carrying its own `if n == 2`. That is what makes the 2→3 scale-out a
//! regeneration instead of a migration: same engine, one more node, and the
//! two-node mechanisms fall away because the renderer stops emitting them.
//!
//! The two regimes, spelled out:
//!
//! | | two nodes | three to five |
//! |---|---|---|
//! | corosync quorum | `two_node: 1`, `wait_for_all: 1` | plain majority |
//! | fence race | asymmetric `pcmk_delay_base` | none — quorum decides |
//! | Pacemaker | (defaults) | `no-quorum-policy=stop` |
//! | DRBD | `fencing resource-and-stonith` + handlers | volume quorum, suspend on loss |
//!
//! `tests::the_invariants_hold_for_every_supported_size` walks every N in
//! 2..=5 and holds all four rows.

use serde::Serialize;

use crate::model::{ClusterDefinition, Regime, COROSYNC_PORT, FENCE_RACE_DELAY_SECS};

/// One rendered STONITH device: `fence_ipmilan`, aimed at exactly one node.
/// IPMI is the only fencing mechanism this appliance has — no sbd, no
/// watchdog, no second level — so this type is deliberately not general.
#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
pub struct FenceDevice {
    /// Pacemaker resource id, `fence-<node>`.
    pub id: String,
    /// The node this device powers off. The delay below protects this node.
    pub target: String,
    /// BMC address the agent connects to.
    pub bmc_address: String,
    pub bmc_username: String,
    /// `pcmk_delay_base`, seconds. A delay on a device is time the *peer*
    /// must wait before killing this device's target — so the preferred node
    /// of a two-node cluster carries the delay on *its* device, and wins the
    /// race. Getting this backwards inverts the preference, which is why the
    /// rendering is here, tested, and not assembled at a call site.
    pub delay_base_secs: u32,
}

/// How DRBD is told to behave for a volume in this cluster — the topology
/// half of replication policy. `lumen-drbd` renders resource files from this
/// rather than deciding for itself.
#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
pub struct ReplicationPolicy {
    /// `fencing resource-and-stonith` with the crm-fence-peer handlers: on a
    /// lost peer, suspend I/O and outdate the peer through Pacemaker before
    /// resuming. Two-node only — it is what makes auto-promote safe without
    /// quorum.
    pub fence_peer_through_pacemaker: bool,
    /// DRBD's own `quorum majority` + `on-no-quorum suspend-io`. Set for
    /// three-replica volumes in the quorum regime, where a majority of
    /// replicas is a meaningful thing to have.
    pub volume_quorum: bool,
}

/// The rendered shape of one cluster: everything `pcs cluster setup` and the
/// fence-device workflow need, derived from the definition in one place.
#[derive(Debug, Clone)]
pub struct ClusterTopology {
    definition: ClusterDefinition,
}

impl ClusterTopology {
    /// The definition is assumed validated — `validate::validate_definition`
    /// is the gate, and it runs before anything renders.
    pub fn new(definition: ClusterDefinition) -> Self {
        ClusterTopology { definition }
    }

    pub fn definition(&self) -> &ClusterDefinition {
        &self.definition
    }

    pub fn regime(&self) -> Regime {
        self.definition.regime()
    }

    /// The corosync.conf for this cluster: knet, both rings, crypto on, and
    /// the quorum section the regime calls for. Rendered whole — corosync.conf
    /// is generated state, never hand-edited, so there is no merge to do.
    pub fn corosync_conf(&self) -> String {
        let mut conf = String::new();
        conf.push_str("# Generated by Lumen. Changes here are overwritten; the cluster\n");
        conf.push_str("# definition in the console is the source of truth.\n");
        conf.push_str("totem {\n");
        conf.push_str("    version: 2\n");
        conf.push_str(&format!("    cluster_name: {}\n", self.definition.name));
        conf.push_str("    transport: knet\n");
        conf.push_str("    crypto_cipher: aes256\n");
        conf.push_str("    crypto_hash: sha256\n");
        conf.push_str("    link_mode: passive\n");
        conf.push_str(&format!("    interface {{\n        linknumber: 0\n        knet_link_priority: 1\n        mcastport: {COROSYNC_PORT}\n    }}\n"));
        conf.push_str(&format!("    interface {{\n        linknumber: 1\n        knet_link_priority: 0\n        mcastport: {}\n    }}\n", COROSYNC_PORT + 1));
        conf.push_str("}\n\n");

        conf.push_str("nodelist {\n");
        for (index, node) in self.definition.nodes.iter().enumerate() {
            conf.push_str("    node {\n");
            conf.push_str(&format!("        name: {}\n", node.name));
            conf.push_str(&format!("        nodeid: {}\n", index + 1));
            conf.push_str(&format!("        ring0_addr: {}\n", node.ring0));
            conf.push_str(&format!("        ring1_addr: {}\n", node.ring1));
            conf.push_str("    }\n");
        }
        conf.push_str("}\n\n");

        conf.push_str("quorum {\n");
        conf.push_str("    provider: corosync_votequorum\n");
        if self.regime() == Regime::TwoNode {
            // two_node keeps one survivor quorate after fencing succeeds;
            // wait_for_all keeps a cold-booting node from claiming quorum
            // alone before it has ever seen its peer.
            conf.push_str("    two_node: 1\n");
            conf.push_str("    wait_for_all: 1\n");
        }
        conf.push_str("}\n\n");

        conf.push_str("logging {\n    to_logfile: no\n    to_syslog: yes\n}\n");
        conf
    }

    /// One `fence_ipmilan` device per node, delays set by the regime. Every
    /// node has exactly one device and every device targets a member — the
    /// invariant the property tests hold for every N.
    pub fn fence_devices(&self) -> Vec<FenceDevice> {
        let preferred = match self.regime() {
            Regime::TwoNode => self.definition.preferred_node.as_deref(),
            // Majority quorum decides who survives; a delay would only slow
            // legitimate fencing down.
            Regime::Quorum => None,
        };
        self.definition
            .nodes
            .iter()
            .map(|node| FenceDevice {
                id: format!("fence-{}", node.name),
                target: node.name.clone(),
                bmc_address: node.bmc.address.clone(),
                bmc_username: node.bmc.username.clone(),
                delay_base_secs: if Some(node.name.as_str()) == preferred {
                    FENCE_RACE_DELAY_SECS
                } else {
                    0
                },
            })
            .collect()
    }

    /// Cluster-wide Pacemaker properties. STONITH is always on — there is no
    /// supported configuration with fencing disabled, and deliberately no
    /// property here that could turn it off.
    pub fn pacemaker_properties(&self) -> Vec<(String, String)> {
        let mut properties = vec![("stonith-enabled".to_string(), "true".to_string())];
        if self.regime() == Regime::Quorum {
            // A partitioned minority stops what it holds rather than serving
            // stale answers. At two nodes this is two_node's business.
            properties.push(("no-quorum-policy".to_string(), "stop".to_string()));
        }
        properties
    }

    /// The replication policy for a volume with `replicas` members in this
    /// cluster. Integrity over availability in both regimes; the mechanism
    /// differs because what a majority means differs.
    pub fn replication_policy(&self, replicas: usize) -> ReplicationPolicy {
        match self.regime() {
            Regime::TwoNode => ReplicationPolicy {
                fence_peer_through_pacemaker: true,
                volume_quorum: false,
            },
            Regime::Quorum => ReplicationPolicy {
                fence_peer_through_pacemaker: false,
                // With two replicas there is no majority to have; the cluster
                // quorum and fencing above are what protect those.
                volume_quorum: replicas >= 3,
            },
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::model::{BmcConfig, MemberNode};
    use std::net::Ipv4Addr;

    fn definition_of(n: usize) -> ClusterDefinition {
        let nodes = (1..=n)
            .map(|i| MemberNode {
                name: format!("node-{i}"),
                ring0: Ipv4Addr::new(10, 10, 0, i as u8),
                ring1: Ipv4Addr::new(192, 168, 10, i as u8),
                bmc: BmcConfig {
                    address: format!("10.20.0.{i}"),
                    username: "ADMIN".into(),
                },
            })
            .collect();
        ClusterDefinition {
            name: "test".into(),
            nodes,
            preferred_node: if n == 2 { Some("node-1".into()) } else { None },
        }
    }

    /// The whole point of this module, held for every supported size at once.
    /// N=2 must carry all three special mechanisms; N>=3 must carry none of
    /// them; and the fence-device and volume-membership invariants hold
    /// everywhere. Exhaustive rather than sampled: the domain is four values.
    #[test]
    fn the_invariants_hold_for_every_supported_size() {
        for n in 2..=5usize {
            let topology = ClusterTopology::new(definition_of(n));
            let conf = topology.corosync_conf();
            let devices = topology.fence_devices();
            let properties = topology.pacemaker_properties();

            // Every node has exactly one fence device, and every device
            // targets a member.
            assert_eq!(devices.len(), n, "N={n}");
            for node in &topology.definition().nodes {
                assert_eq!(
                    devices.iter().filter(|d| d.target == node.name).count(),
                    1,
                    "N={n}: {} must have exactly one fence device",
                    node.name
                );
            }

            // STONITH can never be off, at any size.
            assert!(
                properties.contains(&("stonith-enabled".into(), "true".into())),
                "N={n}"
            );

            if n == 2 {
                assert!(conf.contains("two_node: 1"), "N=2 must be witness-less");
                assert!(conf.contains("wait_for_all: 1"), "N=2 cold boot must wait");
                let delays: Vec<u32> = devices.iter().map(|d| d.delay_base_secs).collect();
                assert!(
                    delays.contains(&FENCE_RACE_DELAY_SECS) && delays.contains(&0),
                    "N=2 fence delays must be asymmetric, got {delays:?}"
                );
                assert!(
                    topology.replication_policy(2).fence_peer_through_pacemaker,
                    "N=2 volumes fence their peer through Pacemaker"
                );
                assert!(
                    !properties.iter().any(|(k, _)| k == "no-quorum-policy"),
                    "N=2 leaves quorum policy to two_node"
                );
            } else {
                assert!(!conf.contains("two_node"), "N={n} must not carry two_node");
                assert!(
                    !conf.contains("wait_for_all"),
                    "N={n} must not carry wait_for_all"
                );
                assert!(
                    devices.iter().all(|d| d.delay_base_secs == 0),
                    "N={n} has no fence race to bias"
                );
                assert!(
                    properties.contains(&("no-quorum-policy".into(), "stop".into())),
                    "N={n} minority must stop"
                );
                assert!(
                    !topology.replication_policy(2).fence_peer_through_pacemaker,
                    "N={n} volumes rely on quorum, not peer fencing"
                );
                assert!(
                    topology.replication_policy(3).volume_quorum,
                    "N={n} three-replica volumes carry their own quorum"
                );
                assert!(
                    !topology.replication_policy(2).volume_quorum,
                    "N={n} two replicas have no majority to count"
                );
            }
        }
    }

    /// The delay protects its target: the preferred node's own device carries
    /// it, so the peer waits and the preferred node shoots first. This is the
    /// one place getting it backwards would silently invert the preference.
    #[test]
    fn the_fence_delay_sits_on_the_preferred_nodes_own_device() {
        let topology = ClusterTopology::new(definition_of(2));
        let devices = topology.fence_devices();
        let preferred = devices.iter().find(|d| d.target == "node-1").unwrap();
        let other = devices.iter().find(|d| d.target == "node-2").unwrap();
        assert_eq!(preferred.delay_base_secs, FENCE_RACE_DELAY_SECS);
        assert_eq!(other.delay_base_secs, 0);
    }

    /// Scale-out is a regeneration, not a migration: the same engine over the
    /// grown definition simply stops emitting the two-node mechanisms.
    #[test]
    fn growing_from_two_to_three_drops_the_two_node_mechanisms() {
        let two = ClusterTopology::new(definition_of(2));
        assert!(two.corosync_conf().contains("two_node: 1"));

        let mut grown = definition_of(2);
        grown.nodes.push(MemberNode {
            name: "node-3".into(),
            ring0: Ipv4Addr::new(10, 10, 0, 3),
            ring1: Ipv4Addr::new(192, 168, 10, 3),
            bmc: BmcConfig {
                address: "10.20.0.3".into(),
                username: "ADMIN".into(),
            },
        });
        grown.preferred_node = None;
        let three = ClusterTopology::new(grown);
        let conf = three.corosync_conf();
        assert!(!conf.contains("two_node"));
        assert!(three.fence_devices().iter().all(|d| d.delay_base_secs == 0));
        assert!(three
            .pacemaker_properties()
            .contains(&("no-quorum-policy".into(), "stop".into())));
    }

    #[test]
    fn the_rendered_conf_names_every_member_on_both_rings() {
        let topology = ClusterTopology::new(definition_of(3));
        let conf = topology.corosync_conf();
        for i in 1..=3 {
            assert!(conf.contains(&format!("name: node-{i}")));
            assert!(conf.contains(&format!("ring0_addr: 10.10.0.{i}")));
            assert!(conf.contains(&format!("ring1_addr: 192.168.10.{i}")));
        }
        assert!(conf.contains("cluster_name: test"));
        assert!(conf.contains("transport: knet"));
        assert!(conf.contains("crypto_cipher: aes256"));
    }
}
